version: "{build}"

clone_folder: c:\gopath\src\gitlab.com\jgillich\autominer

environment:
  GOPATH: c:\gopath

install:
  - git submodule update --init --recursive
  - set PATH=%GOPATH%\bin;C:\msys64\usr\bin;%PATH%
  - set CGO_CFLAGS=-I c:\msys64\mingw64\include -L c:\msys64\mingw64\lib
  - bash -l -c "pacman -S --noconfirm mingw-w64-x86_64-cmake mingw-w64-x86_64-opencl-headers mingw64/mingw-w64-x86_64-headers-git"
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/GeertJohan/go.rice/rice
  - dep ensure -vendor-only
  - set PATH=C:\go;C:\msys64\mingw64\bin;c:/Windows/system32;C:/Windows/System32/WindowsPowerShell/v1.0

before_build:
  - cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=c:\msys64\mingw64 -Hhash -Bhash/build
  - cmake --build hash/build

build_script:
  - go version
  - go env
  - rice embed-go -i ./command
  - go build
