version: "{build}"

clone_folder: c:\gopath\src\gitlab.com\blockforge\blockforge

environment:
  GOPATH: c:\gopath

install:
  - ps: |
      git submodule update --init --recursive
      $env:Path = "$env:GOPATH\bin;C:\msys64\usr\bin;" + $env:Path
      bash -l -c "pacman -S --needed --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-opencl-headers mingw-w64-x86_64-headers-git mingw-w64-x86_64-make" 2>&1 | %{ "$_" }
      $env:Path = ($env:Path.Split(';') | Where-Object { $_ -ne 'C:\msys64\usr\bin' }) -join ';'
      $env:Path = ($env:Path.Split(';') | Where-Object { $_ -ne 'C:/Program Files/Git/usr/bin/' }) -join ';'
      go get -u github.com/golang/dep/cmd/dep github.com/gobuffalo/packr/...
      Invoke-WebRequest -Uri http://www.open-mpi.de/software/hwloc/v1.11/downloads/hwloc-win64-build-1.11.9.zip -OutFile c:\hwloc.zip
      7z x c:\hwloc.zip -oc:\hwloc
      Copy-Item -Force -Recurse c:\hwloc\hwloc-win64-build-1.11.9\* c:\msys64\mingw64
      Invoke-WebRequest -Uri https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/files/1406216/lightOCLSDK.zip -OutFile c:\ocl.zip
      7z x c:\ocl.zip -oc:\ocl
      Copy-Item -Force -Recurse c:\ocl\lib\x86_64\* c:\msys64\mingw64\lib

before_build:
  - ps: |
      cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=c:\msys64\mingw64 -Hhash -Bhash/build
      cmake --build hash/build
      $env:CGO_CFLAGS = "-w -Ofast"
      dep ensure -vendor-only

build_script:
  - ps: |
      go version
      go env
      go generate
      go build -ldflags '-s -w -linkmode external -extldflags "-static"' 2>&1 | %{ "$_" }


after_build:
  - ps: |
      7z a blockforge.zip blockforge.exe

# FIXME tests require opencl dll
#test_script:
#  - ps: |
#      go fmt $(go list ./... | sls -NotMatch '/vendor/')
#      go vet $(go list ./... | sls -NotMatch '/vendor/')
#      go test -race $(go list ./... | sls -NotMatch '/vendor/')

artifacts:
  - path: blockforge.zip
    name: blockforge
