image: fedora:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GOPATH: /go
  REPO_NAME: gitlab.com/blockforge/blockforge
  CGO_CFLAGS: -w -Ofast
  GOARCH: amd64
  GOHOSTOS: linux

before_script:
  - dnf install -y @development-tools bzip2 go hwloc-devel mesa-libGL-devel ocl-icd-devel webkitgtk4-devel cmake
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - export PATH="$GOPATH/bin:$PATH"

stages:
  - prepare
  - build

libhash:
  stage: prepare
  script:
    - cmake -Hhash -Bhash/build
    - cmake --build hash/build
  artifacts:
    untracked: true
    expire_in: 10 min

dep:
  stage: prepare
  script:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure -vendor-only
  artifacts:
    untracked: true
    expire_in: 10 min

test:
  stage: build
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go get -u github.com/gobuffalo/packr/...
    - go generate
    - go build -ldflags '-s -w'
    - tar cjf blockforge-$GOHOSTOS-$GOARCH.tar.bz2 blockforge
    - sha256sum blockforge-$GOHOSTOS-$GOARCH.tar.bz2
  artifacts:
    paths:
      - blockforge-$GOHOSTOS-$GOARCH.tar.bz2
