image: fedora:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GOPATH: /go
  REPO_NAME: gitlab.com/jgilich/autominer

before_script:
  - dnf install -y @development-tools gcc-c++ go hwloc-devel openssl-devel swig cmake
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - prepare
    - test
    - build

ethmimner:
    stage: prepare
    script:
        - cmake -Hcgo/ethminer/ethminer -Bbuild
        - make -C cgo/ethminer/ethminer/build
    artifacts:
        untracked: true

xmrstak:
    stage: prepare
    script:
        - cmake -Hcgo/xmrstak/xmr-stak -Bbuild
        - make -C cgo/xmrstak/xmr-stak/build
    artifacts:
        untracked: true
    
dep:
    stage: prepare
    script:
        - go get -u github.com/golang/dep/cmd/dep
        - $GOPATH/bin/dep ensure
    artifacts:
        untracked: true

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)
    dependencies:
        - prepare

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/autominer
    artifacts:
      paths:
        - autominer
