image: fedora:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GOPATH: /go
  REPO_NAME: gitlab.com/blockforge/blockforge

before_script:
  - dnf install -y @development-tools go hwloc-devel openssl-devel mesa-libGL-devel ocl-icd-devel webkitgtk4-devel cmake
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - export PATH="$GOPATH/bin:$PATH"

stages:
  - prepare
  - test
  - build

libhash:
  stage: prepare
  script:
    - cmake -Hhash -Bhash/build
    - cmake --build hash/build
  artifacts:
    untracked: true

dep:
  stage: prepare
  script:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure -vendor-only
  artifacts:
    untracked: true

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go get -u github.com/GeertJohan/go.rice/rice
    - go generate
    - go build -o $CI_PROJECT_DIR/blockforge
  artifacts:
    paths:
      - blockforge
