image: fedora:latest

variables:
  GOPATH: /go
  REPO_NAME: gitlab.com/jgilich/autominer

before_script:
  - dnf install -y @development-tools go hwloc-devel swig
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - prepare
    - test
    - build
    
dep:
    stage: prepare
    script:
        - go get -u github.com/golang/dep/cmd/dep
        - $GOPATH/bin/dep ensure
    artifacts:
        paths:
          - vendor
    cache:
        paths:
          - vendor


format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/autominer
    artifacts:
      paths:
        - autominer
