# version format
version: "{build}"

clone_folder: c:\gopath\src\gitlab.com\jgillich\autominer

# environment variables
environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\usr\bin;%PATH%
  #- bash.exe -l -c "pacman -Sy asdasd"
  - ls C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
  - git submodule update --init --recursive
  - choco install swig
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go build

# to disable automatic tests
test: off

# to disable deployment
deploy: off
