# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\gitlab.com\jgillich\autominer

# environment variables
environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - choco install swig
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go build

# to disable automatic tests
test: off

# to disable deployment
deploy: off
